### ISSUE TITLE
Ejemplos desactualizadObsolete examplesos

### ISSUE THREAD

**Issue by brayaneider1** [bpmn-io/dmn-js-examples#29] opened 2024-05-22 21:14 UTC
### Describe the Bug

In node.js version 20 we get the following error when running the examples

### Steps to Reproduce

**npm run all**

```

                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\,
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.12.2
```

**Comment by nikku** [comment] 2024-05-23 06:46
You cannot `npm run all` this repository. Please provide steps to reproduce.

**Comment by nikku** [comment] 2024-05-28 22:43
Closing this issue due to missing steps to reproduce.

**Closed as not planned by nikku** 2024-05-28 22:43 UTC
Labels: bug, invalid, needs more information
